In [8]:
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit

In [14]:
df = pd.read_csv("/media/clement/USB DISK/dataMcGill/legend.csv")

col = "agSpe&activated"

df = df[(df[col] == 1) * (df["peptide"] == "OVA")]
classes = df["APL"]

sk = StratifiedShuffleSplit(n_splits=2, test_size=0.2, random_state=42)

strats = sk.split(df, classes)
index_train, index_test = list(strats)

In [22]:
points = [str(i) for i in range(1, 121)]
df[points]

,1,2,3,4,5,6,7,8,9,10,...,111,112,113,114,115,116,117,118,119,120
3437,4.037535,3.617124,3.386477,3.557191,3.953484,3.853183,3.572519,4.251591,5.087401,4.158967,...,2.223287,2.263304,2.486242,2.492789,2.497737,2.249557,2.071854,1.766219,1.907745,1.901578
3439,0.853480,0.862563,0.828128,0.863375,0.839245,0.874292,0.877225,0.874325,0.901768,0.881522,...,2.360667,1.997862,2.161244,2.093356,2.075152,2.097926,2.233687,2.060709,1.982773,2.169770
3440,2.331513,5.125013,3.586917,2.127225,1.549975,1.460498,1.496218,1.435194,1.565200,1.825608,...,1.032650,0.948049,0.919254,0.981171,1.053374,1.069695,1.003030,1.024024,0.993097,0.972691
3441,0.976961,0.938666,0.925919,0.955596,0.966615,0.952683,0.957393,0.956305,1.071362,6.951980,...,1.218814,1.187302,1.202620,1.195949,1.172125,1.190636,1.206771,1.223425,1.218010,1.230613
3442,3.808621,2.935996,2.879496,3.156508,3.301840,2.875048,2.908639,2.970384,3.124416,2.462195,...,2.837737,2.655967,2.937978,2.996286,3.197150,3.040404,2.971910,3.067676,2.855395,2.924434
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.868742,3.192177,2.617210,3.520209,3.372485,3.488760,3.306096,4.072933,4.287191,4.641335
36365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.043177,0.991426,0.896226,0.926406,0.844271,0.831464,0.864859,0.977662,0.901816,1.062734
36367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.014844,1.093768,1.181516,1.037428,1.109472,1.024755,1.093074,1.160743,1.137390,1.033213
36368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.765021,1.722804,1.624424,1.565978,1.500962,1.658870,1.520532,1.351216,1.572852,1.631540
36372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.947865,0.968022,1.126635,1.123714,1.024078,1.683960,0.951287,0.987625,1.183587,1.173092